name: Create issue on commit
on: 
  [pull_request]
env:
      NUMBER: ${{ github.event.number }}
      LABELS: '["enhancement"]'
jobs:
  assign-labels:
      name: Assign Label to the PR
      runs-on: ubuntu-latest
      steps:
      -   name: Add Labels to the PR
          run: |
            echo "Adding applicable labels to the PR $NUMBER"
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/$NUMBER/labels \
            -d '{"labels": '"$LABELS"'}'
