name: Create issue on commit

on:
  pull_request:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "${{ github.event.head_commit.message }}: ${{ github.GITHUB_ACTOR }}",
            "body": "${{ github.event.head_commit.message }}: ${{ github.GITHUB_ACTOR }}  **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
   
    env:
      NUMBER: ${{ github.event.number }}
      LABELS: '["enhancement"]'

    assign-labels:
      name: Assign Label to the PR
      runs-on: ubuntu-latest
      steps:
      -   name: Add Labels to the PR
          run: |
          echo "Adding applicable labels to the PR $NUMBER"
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.Test_Token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues/$NUMBER/labels \
          -d '{"labels": '"$LABELS"'}'