name: Create issue on commit

on: 
  [push,pull_request]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: github.event_name!='pull_request'
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "${{ github.event.head_commit.message }}",
            "body": "${{ github.event.head_commit.message }}"
            }' \
          --fail
  assign-labels:
      name: Assign Label to the PR
      runs-on: ubuntu-latest
      needs: create_issue
      if: github.event_name!='push'
      env:
        NUMBER: ${{ github.event.number }}
        LABELS: '["enhancement"]'
      steps:
      -   name: Add Labels to the PR
          run: |
              echo "Adding applicable labels to the PR $NUMBER"
              curl -L -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ github.repository }}/issues/$NUMBER/labels \
              -d '{"labels": '"$LABELS"'}'
