name: Create issue on Merge to Master and Add Label on MR

on: 
  pull_request:
  push:
    branches:
      -master
jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: github.event_name!='pull_request'
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "${{ github.event.head_commit.message }}",
            "body": "${{ github.event.head_commit.message }}"
            }' \
          --fail
  assign-labels:
      name: Assign Label to the PR
      runs-on: ubuntu-latest
      if: github.event_name!='push'
      env:
        NUMBER: ${{ github.event.number }}
        LABELS: '["enhancement"]'
      steps:
      -   name: Add Labels to the PR
          run: |
              echo "Adding applicable labels to the PR $NUMBER"
              curl -L -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ github.repository }}/issues/$NUMBER/labels \
              -d '{"labels": '"$LABELS"'}'
  run_playwright_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean test
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history